"""init migration

Revision ID: 25714ffdf987
Revises: 
Create Date: 2025-11-16 23:38:07.226516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25714ffdf987'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Имя сотрудника'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Хешированный пароль'),
    sa.Column('balance', sa.Integer(), server_default='1000', nullable=False, comment='Баланс монет'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.CheckConstraint('balance >= 0', name='check_balance_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merch',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Название товара'),
    sa.Column('price', sa.Integer(), nullable=False, comment='Цена в монетах'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.CheckConstraint('price > 0', name='check_price_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('purchases',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.BigInteger(), nullable=False, comment='ID сотрудника'),
    sa.Column('merch_id', sa.BigInteger(), nullable=False, comment='ID товара'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Количество'),
    sa.Column('total_price', sa.Integer(), nullable=False, comment='Общая стоимость'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Дата покупки'),
    sa.CheckConstraint('quantity > 0', name='check_quantity_positive'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merch_id'], ['merch.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.BigInteger(), nullable=False, comment='ID отправителя'),
    sa.Column('receiver_id', sa.BigInteger(), nullable=False, comment='ID получателя'),
    sa.Column('amount', sa.Integer(), nullable=False, comment='Количество монет'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Дата транзакции'),
    sa.CheckConstraint('amount > 0', name='check_amount_positive'),
    sa.ForeignKeyConstraint(['receiver_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('purchases')
    op.drop_table('merch')
    op.drop_table('employees')
    # ### end Alembic commands ###
