"""init migration

Revision ID: 4af00076901a
Revises: 
Create Date: 2025-11-18 17:42:27.179259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4af00076901a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
        sa.Column('team_name', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('team_name')
    )
    op.create_table('users',
        sa.Column('user_id', sa.String(length=255), nullable=False),
        sa.Column('username', sa.String(length=255), nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('team_name', sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(['team_name'], ['teams.team_name'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('pull_requests',
        sa.Column('pull_request_id', sa.String(length=255), nullable=False),
        sa.Column('pull_request_name', sa.String(length=500), nullable=False),
        sa.Column('author_id', sa.String(length=255), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('merged_at', sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('pull_request_id')
    )
    op.create_table('pull_request_reviewers',
        sa.Column('assigned_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('pull_request_id', sa.String(length=255), nullable=False),
        sa.Column('user_id', sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.pull_request_id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('pull_request_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pull_request_reviewers')
    op.drop_table('pull_requests')
    op.drop_table('users')
    op.drop_table('teams')
    # ### end Alembic commands ###
